### ISSUE TITLE
Unable to run this from the command line

### ISSUE THREAD

**Issue by axtonpitt** [lachrist/oghma#1]
Hi there,

I either get this message: 
```
throw [
  ^
Arguments: 
  --nodes   path/to/nodes.json
  --edges   path/to/edges.json
  --recover path/to/recover.swp
 [--profile path/to/firefox-profile]
 [--seminal "A paper EXACT title"]
```

or have a `-bash: command not found` response.

Do you have any tips or instruction on how to use this from the command line?

**Comment by lachrist** [comment]
I updated the repository, can you make it work as explained in the readme?

**Comment by axtonpitt** [comment]
Thanks for the details, looks like I didn't have proper JSON files. However I am now getting this error:

`Error: The geckodriver executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/WebDriver and ensure it can be found on your PATH.
    at findGeckoDriver (/usr/local/lib/node_modules/oghma/node_modules/selenium-webdriver/firefox/index.js:298:11)
    at ServiceBuilder (/usr/local/lib/node_modules/oghma/node_modules/selenium-webdriver/firefox/index.js:410:22)
    at createGeckoDriver (/usr/local/lib/node_modules/oghma/node_modules/selenium-webdriver/firefox/index.js:515:19)
    at Function.createSession (/usr/local/lib/node_modules/oghma/node_modules/selenium-webdriver/firefox/index.js:631:14)
    at createDriver (/usr/local/lib/node_modules/oghma/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/usr/local/lib/node_modules/oghma/node_modules/selenium-webdriver/index.js:642:16)
    at create (/usr/local/lib/node_modules/oghma/driver/index.js:40:62)
    at module.exports (/usr/local/lib/node_modules/oghma/driver/index.js:44:15)
    at module.exports (/usr/local/lib/node_modules/oghma/main.js:77:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/oghma/bin.js:25:1)`

Any ideas how to fix this?

**Comment by lachrist** [comment]
Well do as they say :)
Oghma is based on Selenium to simulate user interaction with the browser.
But I should but that on the readme though...
